import { v4 as uuid } from "uuid";

export const DEPARTAMENTOS = [
  "Producción",
  "Almacén",
  "Administración",
  "Ventas",
  "Mantenimiento",
];

export const seedEmployees = [
  {
    id: uuid(),
    nombre: "Carlos Ramírez Soto",
    documento: "45210983",
    cargo: "Operario",
    departamento: "Producción",
    salarioBase: 350,
    factorHoraExtra: 1.5,
    telefono: "987 654 321",
    fechaIngreso: "2023-02-14",
    estado: "Activo",
  },
  {
    id: uuid(),
    nombre: "María Fernanda López",
    documento: "48123765",
    cargo: "Supervisora",
    departamento: "Producción",
    salarioBase: 480,
    factorHoraExtra: 1.5,
    telefono: "912 345 678",
    fechaIngreso: "2021-06-01",
    estado: "Activo",
  },
  {
    id: uuid(),
    nombre: "Jorge Luis Medina",
    documento: "41987654",
    cargo: "Almacenero",
    departamento: "Almacén",
    salarioBase: 320,
    factorHoraExtra: 1.5,
    telefono: "998 112 233",
    fechaIngreso: "2022-11-20",
    estado: "Activo",
  },
  {
    id: uuid(),
    nombre: "Ana Cecilia Torres",
    documento: "44556677",
    cargo: "Asistente Administrativa",
    departamento: "Administración",
    salarioBase: 400,
    factorHoraExtra: 1.5,
    telefono: "965 432 109",
    fechaIngreso: "2020-03-10",
    estado: "Activo",
  },
  {
    id: uuid(),
    nombre: "Luis Alberto Quispe",
    documento: "40332211",
    cargo: "Técnico de Mantenimiento",
    departamento: "Mantenimiento",
    salarioBase: 370,
    factorHoraExtra: 1.75,
    telefono: "978 654 321",
    fechaIngreso: "2023-09-05",
    estado: "Activo",
  },
  {
    id: uuid(),
    nombre: "Rosa Elvira Huamán",
    documento: "46789123",
    cargo: "Vendedora",
    departamento: "Ventas",
    salarioBase: 340,
    factorHoraExtra: 1.5,
    telefono: "944 223 110",
    fechaIngreso: "2024-01-08",
    estado: "Inactivo",
  },
  {
    id: uuid(),
    nombre: "Pedro Pablo Rojas",
    documento: "43221198",
    cargo: "Operario",
    departamento: "Producción",
    salarioBase: 350,
    factorHoraExtra: 1.5,
    telefono: "935 667 788",
    fechaIngreso: "2022-05-17",
    estado: "Activo",
  },
];
